export const jobs = [
    {
        "no": 1,
        "title": "Customer Service Representative",
        "company": "XYZ Customer Care",
        "location": "Jakarta, Indonesia",
        "maxSalary": "Rp. 1.500.000",
        "minSalary": "Rp. 1.000.000",
        "type": "Full Time",
        "description": "We are seeking a Customer Service Representative to provide excellent service to our clients. You will be responsible for handling customer inquiries and resolving complaints.",
        "requirement": ["Strong communication and interpersonal skills", "Ability to work in a fast-paced environment", "Previous experience in a customer service role is preferred"],
        "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for career advancement", "Training and development programs"],
        "maxUsia": 35,
        "minUsia": 20,
        "minEdu": "SMK",
        "status": "Open",
        "createdAt": "2023-10-01T04:00:00.000Z",
        "updatedAt": "2023-10-10T04:00:00.000Z",
        "closeAt": "2023-11-10T04:00:00.000Z",
        "likes": 150,
        "jumlahPelamar": 78 
    },
    {
        "no": 2,
        "title": "Marketing Assistant",
        "company": "ABC Marketing Agency",
        "location": "Surabaya, Indonesia",
        "maxSalary": "Rp. 1.500.000",
        "minSalary": "Rp. 1.200.000",
        "type": "Full Time",
        "description": "Join our dynamic marketing team to assist with various marketing activities. You will support the development and implementation of marketing campaigns and strategies.",
        "requirement": ["Basic knowledge of marketing principles and strategies", "Strong organizational and multitasking abilities", "Familiarity with social media platforms and digital marketing tools"],
        "benefit": ["Competitive salary and performance-based incentives", "Opportunities for skill development and learning", "Collaborative and innovative work environment"],
        "maxUsia": 30,
        "minUsia": 22,
        "minEdu": "SMA",
        "status": "Open",
        "createdAt": "2023-09-15T04:00:00.000Z",
        "updatedAt": "2023-10-05T04:00:00.000Z",
        "closeAt": "2023-11-05T04:00:00.000Z",
        "likes": 180,
        "jumlahPelamar": 71 
    },
    // Entry 3
{
    "no": 3,
    "title": "Junior Graphic Designer",
    "company": "Design Prodigy Studio",
    "location": "Bandung, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.000.000",
    "type": "Full Time",
    "description": "We are looking for a creative and talented Junior Graphic Designer to assist in the development of various design projects. You will work closely with the design team to create engaging visual content.",
    "requirement": ["Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign)", "Strong understanding of design principles and techniques", "Ability to work collaboratively in a team environment"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for professional growth and skill enhancement", "Exposure to diverse design projects and clients"],
    "maxUsia": 28,
    "minUsia": 21,
    "minEdu": "SMA",
    "status": "Open",
    "createdAt": "2023-09-18T04:00:00.000Z",
    "updatedAt": "2023-10-06T04:00:00.000Z",
    "closeAt": "2023-11-06T04:00:00.000Z",
    "likes": 120,
    "jumlahPelamar": 20
},
// Entry 4
{
    "no": 4,
    "title": "Content Writer",
    "company": "WordCraft Solutions",
    "location": "Yogyakarta, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.200.000",
    "type": "Full Time",
    "description": "Join our team as a Content Writer to create compelling and engaging content for various platforms. You will be responsible for producing high-quality and SEO-friendly content that resonates with our target audience.",
    "requirement": ["Excellent writing and editing skills", "Familiarity with SEO best practices and keyword research", "Ability to meet deadlines and work under pressure"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for career advancement and professional development", "Flexible work hours and remote work options"],
    "maxUsia": 32,
    "minUsia": 22,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-09-20T04:00:00.000Z",
    "updatedAt": "2023-10-08T04:00:00.000Z",
    "closeAt": "2023-11-08T04:00:00.000Z",
    "likes": 160,
    "jumlahPelamar": 55 
},
// Entry 5
{
    "no": 5,
    "title": "Sales Representative",
    "company": "Pro Sales Solutions",
    "location": "Surabaya, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.000.000",
    "type": "Full Time",
    "description": "Seeking a motivated Sales Representative to promote and sell our products to potential customers. You will play a key role in building and maintaining strong customer relationships and achieving sales targets.",
    "requirement": ["Proven experience in sales or customer service", "Strong communication and negotiation skills", "Goal-oriented and self-motivated individual"],
    "benefit": ["Competitive salary and attractive commission structure", "Comprehensive sales training and professional development", "Opportunities for career growth within the organization"],
    "maxUsia": 35,
    "minUsia": 25,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-09-22T04:00:00.000Z",
    "updatedAt": "2023-10-10T04:00:00.000Z",
    "closeAt": "2023-11-10T04:00:00.000Z",
    "likes": 140,
    "jumlahPelamar": 72 
},
// Entry 6
{
    "no": 6,
    "title": "Data Entry Clerk",
    "company": "DataWorks Inc.",
    "location": "Jakarta, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.200.000",
    "type": "Full Time",
    "description": "We are in need of a meticulous and detail-oriented Data Entry Clerk to input and manage data accurately. Your responsibilities include verifying data and maintaining accurate records.",
    "requirement": ["Proficiency in data entry and management", "Strong attention to detail and accuracy", "Ability to work efficiently in a fast-paced environment"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for skill development and career advancement", "Supportive and collaborative work environment"],
    "maxUsia": 30,
    "minUsia": 20,
    "minEdu": "SMA",
    "status": "Open",
    "createdAt": "2023-09-25T04:00:00.000Z",
    "updatedAt": "2023-10-12T04:00:00.000Z",
    "closeAt": "2023-11-12T04:00:00.000Z",
    "likes": 150,
    "jumlahPelamar": 76 
},
// Entry 7
{
    "no": 7,
    "title": "Junior Web Developer",
    "company": "WebWise Solutions",
    "location": "Bandung, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.000.000",
    "type": "Full Time",
    "description": "Join our team as a Junior Web Developer to assist in the development and maintenance of web applications. You will work alongside a team of experienced developers and contribute to the creation of innovative and user-friendly websites.",
    "requirement": ["Proficiency in HTML, CSS, and JavaScript", "Familiarity with web development frameworks and libraries", "Passion for learning and staying updated with the latest web technologies"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for skill enhancement and career growth", "Exposure to diverse and challenging projects"],
    "maxUsia": 28,
    "minUsia": 21,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-09-28T04:00:00.000Z",
    "updatedAt": "2023-10-15T04:00:00.000Z",
    "closeAt": "2023-11-15T04:00:00.000Z",
    "likes": 160,
    "jumlahPelamar": 38 
},
// Entry 8
{
    "no": 8,
    "title": "Administrative Assistant",
    "company": "AdminPro Solutions",
    "location": "Yogyakarta, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.200.000",
    "type": "Full Time",
    "description": "We are seeking an efficient and organized Administrative Assistant to support our daily office operations. Your responsibilities will include handling administrative tasks and providing assistance to the management team.",
    "requirement": ["Strong organizational and time management skills", "Proficiency in Microsoft Office applications", "Ability to multitask and prioritize tasks effectively"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for career advancement and professional development", "Collaborative and supportive work environment"],
    "maxUsia": 32,
    "minUsia": 22,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-09-30T04:00:00.000Z",
    "updatedAt": "2023-10-18T04:00:00.000Z",
    "closeAt": "2023-11-18T04:00:00.000Z",
    "likes": 170,
    "jumlahPelamar": 81 
},
// Entry 9
{
    "no": 9,
    "title": "Warehouse Associate",
    "company": "LogiWorks Logistics",
    "location": "Surabaya, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.000.000",
    "type": "Full Time",
    "description": "We are looking for a reliable and hardworking Warehouse Associate to assist in the daily operations of our warehouse. Your responsibilities will include receiving and processing incoming stock and ensuring efficient stock management.",
    "requirement": ["Ability to lift and move heavy objects", "Strong attention to detail and accuracy", "Previous experience in a warehouse or logistics role is preferred"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for career growth and advancement", "Safe and supportive working environment"],
    "maxUsia": 35,
    "minUsia": 25,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-02T04:00:00.000Z",
    "updatedAt": "2023-10-20T04:00:00.000Z",
    "closeAt": "2023-11-20T04:00:00.000Z",
    "likes": 180,
    "jumlahPelamar": 94 
},
// Entry 10
{
    "no": 10,
    "title": "Junior Accountant",
    "company": "AccuCount Financial Services",
    "location": "Jakarta, Indonesia",
    "maxSalary": "Rp. 1.500.000",
    "minSalary": "Rp. 1.200.000",
    "type": "Full Time",
    "description": "Join our team as a Junior Accountant to assist in managing financial transactions and preparing financial reports. You will work under the guidance of senior accountants and contribute to the overall financial operations of the company.",
    "requirement": ["Basic knowledge of accounting principles and practices", "Proficiency in using accounting software and tools", "Strong analytical and problem-solving skills"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for professional development and career advancement", "Supportive and collaborative work environment"],
    "maxUsia": 30,
    "minUsia": 20,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-10-05T04:00:00.000Z",
    "updatedAt": "2023-10-23T04:00:00.000Z",
    "closeAt": "2023-11-23T04:00:00.000Z",
    "likes": 190,
    "jumlahPelamar": 23 
},
// Entry 11
{
    "no": 11,
    "title": "Social Media Specialist",
    "company": "BuzzConnect Marketing Agency",
    "location": "Surabaya, Indonesia",
    "maxSalary": "Rp. 1.800.000",
    "minSalary": "Rp. 1.300.000",
    "type": "Full Time",
    "description": "We are seeking a talented Social Media Specialist to develop and implement social media strategies for our clients. You will be responsible for creating engaging content and managing online interactions to enhance brand awareness and engagement.",
    "requirement": ["Proven experience in managing social media platforms", "Strong understanding of social media analytics and tools", "Creative thinking and excellent communication skills"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for skill enhancement and career growth", "Dynamic and collaborative work environment"],
    "maxUsia": 32,
    "minUsia": 22,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-07T04:00:00.000Z",
    "updatedAt": "2023-10-25T04:00:00.000Z",
    "closeAt": "2023-11-25T04:00:00.000Z",
    "likes": 200,
    "jumlahPelamar": 63 
},
// Entry 12
{
    "no": 12,
    "title": "Customer Service Representative",
    "company": "ServiceFirst Solutions",
    "location": "Bandung, Indonesia",
    "maxSalary": "Rp. 1.700.000",
    "minSalary": "Rp. 1.100.000",
    "type": "Full Time",
    "description": "Join our team as a Customer Service Representative to provide exceptional service and support to our customers. You will handle inquiries, resolve complaints, and ensure customer satisfaction through effective communication and problem-solving skills.",
    "requirement": ["Excellent communication and interpersonal skills", "Ability to remain calm and patient in challenging situations", "Strong problem-solving and decision-making abilities"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for career development and growth", "Supportive and collaborative work environment"],
    "maxUsia": 35,
    "minUsia": 25,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-10-09T04:00:00.000Z",
    "updatedAt": "2023-10-27T04:00:00.000Z",
    "closeAt": "2023-11-27T04:00:00.000Z",
    "likes": 210,
    "jumlahPelamar": 23 
},
// Entry 13
{
    "no": 13,
    "title": "HR Assistant",
    "company": "PeopleConnect HR Solutions",
    "location": "Yogyakarta, Indonesia",
    "maxSalary": "Rp. 1.600.000",
    "minSalary": "Rp. 1.100.000",
    "type": "Full Time",
    "description": "We are looking for an organized and detail-oriented HR Assistant to support our HR activities. Your responsibilities will include maintaining employee records, coordinating HR projects, and assisting in recruitment and onboarding processes.",
    "requirement": ["Basic knowledge of HR processes and practices", "Strong organizational and multitasking skills", "Ability to maintain confidentiality and professionalism"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for career advancement and professional development", "Collaborative and supportive work environment"],
    "maxUsia": 32,
    "minUsia": 22,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-10-11T04:00:00.000Z",
    "updatedAt": "2023-10-29T04:00:00.000Z",
    "closeAt": "2023-11-29T04:00:00.000Z",
    "likes": 220,
    "jumlahPelamar": 100 
},
// Entry 14
{
    "no": 14,
    "title": "IT Support Specialist",
    "company": "TechPro Solutions",
    "location": "Jakarta, Indonesia",
    "maxSalary": "Rp. 1.800.000",
    "minSalary": "Rp. 1.400.000",
    "type": "Full Time",
    "description": "Join our team as an IT Support Specialist to provide technical assistance and support to our internal staff. You will troubleshoot issues, set up equipment, and ensure smooth functioning of all IT systems.",
    "requirement": ["Experience in providing technical support and troubleshooting", "Knowledge of IT systems and network administration", "Strong problem-solving and communication skills"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for professional development and career growth", "Supportive and collaborative work environment"],
    "maxUsia": 35,
    "minUsia": 25,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-13T04:00:00.000Z",
    "updatedAt": "2023-10-31T04:00:00.000Z",
    "closeAt": "2023-11-31T04:00:00.000Z",
    "likes": 230,
    "jumlahPelamar": 45 
},
// Entry 15
{
    "no": 15,
    "title": "Marketing Associate",
    "company": "Marketer's Hub",
    "location": "Surabaya, Indonesia",
    "maxSalary": "Rp. 1.600.000",
    "minSalary": "Rp. 1.200.000",
    "type": "Full Time",
    "description": "We are searching for a dynamic and creative Marketing Associate to contribute to our marketing strategies and campaigns. You will assist in the development of marketing materials and initiatives to drive brand awareness and lead generation.",
    "requirement": ["Basic understanding of marketing principles and techniques", "Strong communication and interpersonal skills", "Ability to work in a fast-paced and dynamic environment"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for career advancement and skill development", "Collaborative and innovative work culture"],
    "maxUsia": 30,
    "minUsia": 20,
    "minEdu": "S1",
    "status": "Open",
    "createdAt": "2023-10-15T04:00:00.000Z",
    "updatedAt": "2023-11-02T04:00:00.000Z",
    "closeAt": "2023-12-02T04:00:00.000Z",
    "likes": 240,
    "jumlahPelamar": 32 
},
// Entry 16
{
    "no": 16,
    "title": "Junior Software Engineer",
    "company": "CodeCraft Tech Solutions",
    "location": "Bandung, Indonesia",
    "maxSalary": "Rp. 1.800.000",
    "minSalary": "Rp. 1.400.000",
    "type": "Full Time",
    "description": "Join our team as a Junior Software Engineer to assist in the development and maintenance of software applications. You will work with a team of experienced engineers to create high-quality and efficient code for various projects.",
    "requirement": ["Proficiency in programming languages such as Java, Python, or C++", "Understanding of software development lifecycle and methodologies", "Passion for learning and exploring new technologies"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for skill enhancement and professional growth", "Exposure to challenging and innovative projects"],
    "maxUsia": 28,
    "minUsia": 21,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-17T04:00:00.000Z",
    "updatedAt": "2023-11-04T04:00:00.000Z",
    "closeAt": "2023-12-04T04:00:00.000Z",
    "likes": 250,
    "jumlahPelamar": 21 
},
// Entry 17
{
    "no": 17,
    "title": "Accounting Assistant",
    "company": "AccuPro Accounting Solutions",
    "location": "Yogyakarta, Indonesia",
    "maxSalary": "Rp. 1.600.000",
    "minSalary": "Rp. 1.200.000",
    "type": "Full Time",
    "description": "We are seeking an organized and detail-oriented Accounting Assistant to support our accounting and finance team. You will be responsible for managing invoices, processing transactions, and assisting in financial reporting.",
    "requirement": ["Basic knowledge of accounting principles and practices", "Proficiency in using accounting software and tools", "Strong attention to detail and accuracy"],
    "benefit": ["Competitive salary and performance-based incentives", "Opportunities for professional development and career advancement", "Supportive and collaborative work environment"],
    "maxUsia": 32,
    "minUsia": 22,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-19T04:00:00.000Z",
    "updatedAt": "2023-11-06T04:00:00.000Z",
    "closeAt": "2023-12-06T04:00:00.000Z",
    "likes": 260,
    "jumlahPelamar": 32 
},
// Entry 18
{
    "no": 18,
    "title": "Logistics Coordinator",
    "company": "LogiPro Logistics",
    "location": "Surabaya, Indonesia",
    "maxSalary": "Rp. 1.700.000",
    "minSalary": "Rp. 1.300.000",
    "type": "Full Time",
    "description": "We are looking for a proactive and detail-oriented Logistics Coordinator to oversee the movement of goods and materials. You will be responsible for managing logistics operations and ensuring timely and efficient delivery.",
    "requirement": ["Strong organizational and multitasking skills", "Understanding of supply chain and logistics processes", "Ability to work in a fast-paced and dynamic environment"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for career growth and development", "Supportive and collaborative work culture"],
    "maxUsia": 35,
    "minUsia": 25,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-21T04:00:00.000Z",
    "updatedAt": "2023-11-08T04:00:00.000Z",
    "closeAt": "2023-12-08T04:00:00.000Z",
    "likes": 270,
    "jumlahPelamar": 64
},
// Entry 19
{
    "no": 19,
    "title": "Graphic Design Intern",
    "company": "DesignPro Agency",
    "location": "Jakarta, Indonesia",
    "maxSalary": "Rp. 1.300.000",
    "minSalary": "Rp. 800.000",
    "type": "Internship",
    "description": "We are offering an exciting opportunity for a Graphic Design Intern to gain hands-on experience in the field of graphic design. You will work closely with our design team and assist in the creation of visual content for various projects.",
    "requirement": ["Basic knowledge of design software and tools", "Passion for creativity and visual communication", "Enrollment in a relevant design or arts program"],
    "benefit": ["Opportunities for learning and skill development", "Exposure to real-world design projects and clients", "Supportive and collaborative work environment"],
    "maxUsia": 25,
    "minUsia": 18,
    "minEdu": "SMA",
    "status": "Open",
    "createdAt": "2023-10-23T04:00:00.000Z",
    "updatedAt": "2023-11-10T04:00:00.000Z",
    "closeAt": "2023-12-10T04:00:00.000Z",
    "likes": 280,
    "jumlahPelamar": 98
},
// Entry 20
{
    "no": 20,
    "title": "Content Marketing Manager",
    "company": "ContentCraft Solutions",
    "location": "Bandung, Indonesia",
    "maxSalary": "Rp. 2.000.000",
    "minSalary": "Rp. 1.500.000",
    "type": "Full Time",
    "description": "We are seeking a strategic and creative Content Marketing Manager to lead our content marketing initiatives. You will be responsible for developing content strategies, managing content creation, and analyzing the effectiveness of content campaigns.",
    "requirement": ["Proven experience in content marketing and strategy development", "Strong understanding of digital marketing and SEO principles", "Excellent leadership and communication skills"],
    "benefit": ["Competitive salary and performance-based bonuses", "Opportunities for career advancement and professional development", "Dynamic and innovative work environment"],
    "maxUsia": 40,
    "minUsia": 30,
    "minEdu": "SMK",
    "status": "Open",
    "createdAt": "2023-10-25T04:00:00.000Z",
    "updatedAt": "2023-11-12T04:00:00.000Z",
    "closeAt": "2023-12-1,2T04:00:00.000Z",
    "likes": 290,
    "jumlahPelamar": 32

}
];


